assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    java:           %java_path%
    filters:
        cssrewrite: ~
        coffee:
            bin:        %project.packages_dir%/.bin/coffee
        less:
            node:       %node_path%
            node_paths: [ %project.packages_dir% ]
        yui_css:
            jar:        %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        yui_js:
            jar:        %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

    assets:
        head_javascripts:
            filters: ?yui_js
            inputs:
                - %project.components_dir%/html5shiv/src/html5shiv.js
            output: js/head.js

        foot_javascripts:
            filters: ?yui_js
            inputs:
                - %project.components_dir%/jquery/jquery.js
                - %project.components_dir%/underscore/underscore.js
            output: js/foot.js

        project_coffees:
            filters: coffee
            inputs:
                #coffescript files here

        stylesheets:
            filters: ?yui_css
            inputs:
                - @project_lesses
            output: css/styles.css

        project_lesses:
            filters: less
            inputs:
                - %project.components_dir%/bootstrap/less/bootstrap.less
