twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        layout:       '::base.html.twig'
    form:
        resources:
            - '::form_div_layout.html.twig'
